config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "books#index"
  resources :books do
    resources :copies
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :copies

  validates :title, presence: true
  validates :author, presence: true
  validates :isbn, presence: true
end

app/models/copy.rb
class Copy < ApplicationRecord
  belongs_to :book

  validates :book_id, presence: true
  # validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.sort_by(&:title)
  end

  def show
    @book = Book.find(params[:id])
    @copies = Book.find(params[:id]).copies
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "Book edited."
      redirect_to books_path
    else
      render "edit"
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to books_path
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "New Book created."
      redirect_to books_path
    else
      render "new"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn)
  end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :get_book
  before_action :set_copy, only: [:show, :edit, :update, :destroy]
  def index
    @copies = @book.copies
  end

  def new
    @copy = @book.copies.build
    render "./books/copies/new"
  end

  def show
  end

  def edit
    @copy = Copy.find(params[:id])
    render "books/copies/edit"
  end

  def create
    @copy = @book.copies.build(copy_params)
      if @copy.save
        redirect_to book_path(@book)
      else
        redirect_to new_book_copy_path(@book)
      end
  end

  def update
    if @copy.update(copy_params)
      redirect_to book_path(@book)
    else
      redirect_to edit_book_copy_path(@book,@copy)
    end
  end

  def destroy
    @copy.destroy
    redirect_to book_path(@book)
  end

  private

  def get_book
    @book = Book.find(params[:book_id])
  end

  def set_copy
    @copy = @book.copies.find(params[:id])
  end

  def copy_params
    params.require(:copy).permit(:book_id, :due_date, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/copies/edit.html.erb
Edit a copy here!

<%= form_for [@book, @copy] do |f| %>
  <%= f.label(:book_id) %>
  <%= f.text_field(:book_id) %>
  <%= f.label(:due_date) %>
  <%= f.text_field(:due_date) %>
  <%= f.label(:user_id) %>
  <%= f.text_field(:user_id) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/books/copies/new.html.erb
Create a new copy here!

<%= form_for [@book, @copy] do |f| %>
  <%= f.label(:book_id) %>
  <%= f.text_field(:book_id) %>
  <%= f.label(:due_date) %>
  <%= f.text_field(:due_date) %>
  <%= submit_tag("Submit") %>
<% end %>

app/views/books/edit.html.erb
Edit a book here!

<%= form_for(@book) do |f| %>
  <%= label(:book, :title) %>
  <%= text_field(:book, :title) %>
  <%= label(:book, :author) %>
  <%= text_field(:book, :author) %>
  <%= label(:book, :isbn) %>
  <%= text_field(:book, :isbn) %>
  <input value="Send" type="submit"/>
<% end %>

app/views/books/index.html.erb
<h1>My Books</h1>
<ul>
  <% for book in @books %>
    <li><%= link_to book.title, book_path(book) %>, <%= book.author %>; ISBN: <%= book.isbn %></li>
  <% end %>
</ul>
<%= link_to 'Add a book', new_book_path  %>
<br/>
<br/>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path  %> |
  <%= link_to "Login", new_user_session_path  %>
<% end %>

app/views/books/new.html.erb
Create a new book here!

<%= form_for(Book.new) do |f| %>
  <%= f.label(:title) %>
  <%= f.text_field(:title) %>
  <%= f.label(:author) %>
  <%= f.text_field(:author) %>
  <%= f.label(:isbn) %>
  <%= f.text_field(:isbn) %>
  <input value="Send" type="submit"/>
<% end %>

app/views/books/show.html.erb
<h1> <%= @book.title %> </h1>
<%= form_for (@book), :html => { :method => :delete } do |f| %>
  <input value="Delete book" type="submit"/>
<% end %>

<ul>
  <% if @copies.length >= 1 %>
    <% for copy in @copies %>
      <% if copy.user_id %>
        <li>Copy <%= copy.id %>; currently on loan to <%= User.find(copy.user_id).email %>, due to be returned on <%= copy.due_date %> </li>
        <% if copy.user_id == current_user.id %>
          <%= link_to 'Return copy', edit_book_copy_path(@book, copy, user_id: nil) %>
        <% end %>
      <% else %>
        <li>Copy <%= copy.id %>; not currently on loan. </li>
        <%= link_to 'Checkout copy', edit_book_copy_path(@book, copy, current_user.id) %>
      <% end %>
      <%= form_for [@book, copy], :html => { :method => :delete } do |f| %>
        <input value="Delete copy" type="submit"/>
      <% end %>
        <%#= link_to 'Edit copy', edit_book_copy_path(@book, copy) %>
      <br/>
      <br/>
      </li>
    <% end %>
  <% else %>
    No copies of this book were found
  <% end %>
</ul>

<%= link_to 'Add a copy', new_book_copy_path(@book) %>
</br>
<%= link_to 'Back to Home', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookishRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>